all:CPPHW3-1 CPPHW3-2 CPPHW3-3 CPPHW3-4 CPPHW3-5 CPPHW3-6

CPPHW3-1:CPPHW3-1.o
	g++ -std=c++11 -Wall -o CPPHW3-1 CPPHW3-1.o

CPPHW3-1.o:CPPHW3-1.cpp
	g++ -std=c++11 -Wall -c CPPHW3-1.cpp
	
CPPHW3-2:CPPHW3-2.o
	g++ -std=c++11 -Wall -o CPPHW3-2 CPPHW3-2.o

CPPHW3-2.o:CPPHW3-2.cpp
	g++ -std=c++11 -Wall -c CPPHW3-2.cpp

CPPHW3-3:CPPHW3-3.o
	g++ -std=c++11 -Wall -o CPPHW3-3 CPPHW3-3.o

CPPHW3-3.o:CPPHW3-3.cpp
	g++ -std=c++11 -Wall -c CPPHW3-3.cpp

CPPHW3-4:CPPHW3-4.o
	g++ -std=c++11 -Wall -o CPPHW3-4 CPPHW3-4.o

CPPHW3-4.o:CPPHW3-4.cpp
	g++ -std=c++11 -Wall -c CPPHW3-4.cpp
	
CPPHW3-5:CPPHW3-5.o
	g++ -std=c++11 -Wall -o CPPHW3-5 CPPHW3-5.o

CPPHW3-5.o:CPPHW3-5.cpp
	g++ -std=c++11 -Wall -c CPPHW3-5.cpp

CPPHW3-6:CPPHW3-6.o
	g++ -std=c++11 -Wall -o CPPHW3-6 CPPHW3-6.o

CPPHW3-6.o:CPPHW3-6.cpp
	g++ -std=c++11 -Wall -c CPPHW3-6.cpp

dep:
	echo "Do nothing"

clean:
	rm -f CPPHW3-1 CPPHW3-2 CPPHW3-3 CPPHW3-4 CPPHW3-5 CPPHW3-6 *.o *~*.*~
