all:CPPHW2-1 CPPHW2-2 CPPHW2-3 CPPHW2-4 CPPHW2-5 CPPHW2-6

CPPHW2-1:CPPHW2-1.o
	g++ -std=c++11 -Wall -o CPPHW2-1 CPPHW2-1.o

CPPHW2-1.o:CPPHW2-1.cpp
	g++ -std=c++11 -Wall -c CPPHW2-1.cpp
	
CPPHW2-2:CPPHW2-2.o
	g++ -std=c++11 -Wall -o CPPHW2-2 CPPHW2-2.o

CPPHW2-2.o:CPPHW2-2.cpp
	g++ -std=c++11 -Wall -c CPPHW2-2.cpp

CPPHW2-3:CPPHW2-3.o
	g++ -std=c++11 -Wall -o CPPHW2-3 CPPHW2-3.o

CPPHW2-3.o:CPPHW2-3.cpp
	g++ -std=c++11 -Wall -c CPPHW2-3.cpp

CPPHW2-4:CPPHW2-4.o
	g++ -std=c++11 -Wall -o CPPHW2-4 CPPHW2-4.o

CPPHW2-4.o:CPPHW2-4.cpp
	g++ -std=c++11 -Wall -c CPPHW2-4.cpp
	
CPPHW2-5:CPPHW2-5.o
	g++ -std=c++11 -Wall -o CPPHW2-5 CPPHW2-5.o

CPPHW2-5.o:CPPHW2-5.cpp
	g++ -std=c++11 -Wall -c CPPHW2-5.cpp

CPPHW2-6:CPPHW2-6.o
	g++ -std=c++11 -Wall -o CPPHW2-6 CPPHW2-6.o

CPPHW2-6.o:CPPHW2-6.cpp
	g++ -std=c++11 -Wall -c CPPHW2-6.cpp

dep:
	echo "Do nothing"

clean:
	rm -f CPPHW2-1 CPPHW2-2 CPPHW2-3 CPPHW2-4 CPPHW2-5 CPPHW2-6 *.o *~*.*~
