all:CPPHW5-1 CPPHW5-2 CPPHW5-3 CPPHW5-4 CPPHW5-5 CPPHW5-6

CPPHW5-1:CPPHW5-1.o
	g++ -std=c++11 -Wall -o CPPHW5-1 CPPHW5-1.o

CPPHW5-1.o:CPPHW5-1.cpp
	g++ -std=c++11 -Wall -c CPPHW5-1.cpp
	
CPPHW5-2:CPPHW5-2.o
	g++ -std=c++11 -Wall -o CPPHW5-2 CPPHW5-2.o

CPPHW5-2.o:CPPHW5-2.cpp
	g++ -std=c++11 -Wall -c CPPHW5-2.cpp

CPPHW5-3:CPPHW5-3.o
	g++ -std=c++11 -Wall -o CPPHW5-3 CPPHW5-3.o

CPPHW5-3.o:CPPHW5-3.cpp
	g++ -std=c++11 -Wall -c CPPHW5-3.cpp

CPPHW5-4:CPPHW5-4.o
	g++ -std=c++11 -Wall -o CPPHW5-4 CPPHW5-4.o

CPPHW5-4.o:CPPHW5-4.cpp
	g++ -std=c++11 -Wall -c CPPHW5-4.cpp
	
CPPHW5-5:CPPHW5-5.o
	g++ -std=c++11 -Wall -o CPPHW5-5 CPPHW5-5.o

CPPHW5-5.o:CPPHW5-5.cpp
	g++ -std=c++11 -Wall -c CPPHW5-5.cpp

CPPHW5-6:CPPHW5-6.o
	g++ -std=c++11 -Wall -o CPPHW5-6 CPPHW5-6.o

CPPHW5-6.o:CPPHW5-6.cpp
	g++ -std=c++11 -Wall -c CPPHW5-6.cpp

dep:
	echo "Do nothing"

clean:
	rm -f CPPHW5-1 CPPHW5-2 CPPHW5-3 CPPHW5-4 CPPHW5-5 CPPHW5-6 *.o *~*.*~
