all:CPPHW4-1 CPPHW4-2 CPPHW4-3 CPPHW4-4 CPPHW4-5

CPPHW4-1:CPPHW4-1.o
	g++ -std=c++11 -Wall -o CPPHW4-1 CPPHW4-1.o

CPPHW4-1.o:CPPHW4-1.cpp
	g++ -std=c++11 -Wall -c CPPHW4-1.cpp
	
CPPHW4-2:CPPHW4-2.o
	g++ -std=c++11 -Wall -o CPPHW4-2 CPPHW4-2.o

CPPHW4-2.o:CPPHW4-2.cpp
	g++ -std=c++11 -Wall -c CPPHW4-2.cpp

CPPHW4-3:CPPHW4-3.o
	g++ -std=c++11 -Wall -o CPPHW4-3 CPPHW4-3.o

CPPHW4-3.o:CPPHW4-3.cpp
	g++ -std=c++11 -Wall -c CPPHW4-3.cpp

CPPHW4-4:CPPHW4-4.o
	g++ -std=c++11 -Wall -o CPPHW4-4 CPPHW4-4.o

CPPHW4-4.o:CPPHW4-4.cpp
	g++ -std=c++11 -Wall -c CPPHW4-4.cpp
	
CPPHW4-5:CPPHW4-5.o
	g++ -std=c++11 -Wall -o CPPHW4-5 CPPHW4-5.o

CPPHW4-5.o:CPPHW4-5.cpp
	g++ -std=c++11 -Wall -c CPPHW4-5.cpp

dep:
	echo "Do nothing"

clean:
	rm -f CPPHW4-1 CPPHW4-2 CPPHW4-3 CPPHW4-4 CPPHW4-5 *.o *~*.*~
